version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27117:27117
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container: